//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_project_v0._0._2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public string feedbackID { get; set; }
        public string userID { get; set; }
        public string login { get; set; }
        public string feedback1 { get; set; }
        public System.DateTime dateFeedback { get; set; }
    
        public virtual UsersBD UsersBD { get; set; }
    }
}
