//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_project_v0._0._2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Session = new HashSet<Session>();
        }
    
        public string filmID { get; set; }
        public string filmName { get; set; }
        public Nullable<int> year { get; set; }
        public byte[] poster { get; set; }
        public string plotDescription { get; set; }
        public string genres { get; set; }
        public Nullable<float> rating { get; set; }
        public string countries { get; set; }
        public string director { get; set; }
        public string actors { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> premiereDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
    }
}
